image: Visual Studio 2019

install:
  - git submodule update --init --recursive

build_script: rake "create_linux_build[9.0.46, %APPVEYOR_BUILD_FOLDER%]"

artifacts:
  - path: "*.tar.gz"
    name: Linux

skip_commits:
  files:
    - "*.md"

skip_branch_with_pr: true

skip_tags: true

pull_requests:
  do_not_increment_build_number: true
